export const PLAYER_STATE = {
  LOBBY: 'LOBBY',
  ANSWERING: 'ANSWERING',
  SUBMITTED_WAITING: 'SUBMITTED_WAITING',
  CORRECT_WAITING_NEXT: 'CORRECT_WAITING_NEXT',
  ELIMINATED: 'ELIMINATED',
  WINNER: 'WINNER',
  UNKNOWN: 'UNKNOWN',
} as const;

export type PlayerState = (typeof PLAYER_STATE)[keyof typeof PLAYER_STATE];
